<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-index','monsterat') }}"><span class="mi"></span><span class="txt">Home Default</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','pricing']) }}"><span class="mi"></span><span class="txt">Home Pricing</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','products']) }}"><span class="mi"></span><span class="txt">Home Products</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','history']) }}"><span class="mi"></span><span class="txt">Home History</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','popular-video']) }}"><span class="mi"></span><span class="txt">Home Popular</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','animated']) }}"><span class="mi"></span><span class="txt">Home Animated</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','one_page']) }}"><span class="mi"></span><span class="txt">Home One Page</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','simple']) }}"><span class="mi"></span><span class="txt">Home Simple</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','popular-slider']) }}"><span class="mi"></span><span class="txt">Home Popular</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','store']) }}"><span class="mi"></span><span class="txt">Home Store</span><span class="di icon-arrow-right9"></span></a></li>
<li class="menu-item" data-mm="false" data-mmc="2"><a href="{{ route('monsterat-pages',['monsterat','shop']) }}"><span class="mi"></span><span class="txt">Home Shop</span><span class="di icon-arrow-right9"></span></a></li>
