@extends('front.clothing.layout.layout')
@section('breadcrumb')
    @include('front.clothing.layout.breadcrumb')
@endsection
@section('content')
    @include('front.clothing.section.compare')
    @include('front.clothing.section.new_arrival')
    @include('front.clothing.section.quickview')
@endsection
